version: '3.8'

services:
  app:
    image: sunethchinthaka/dockerspringbootdemo:0.0.1
    ports:
      - 8080:8080
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/dockerdemodb?autoReconnect=true&allowPublicKeyRetrieval=true&useSSL=false
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    depends_on:
      - db
    command: ["sh", "-c", "sleep 30 && java $JAVA_OPTS -jar app.jar"]

  db:
    image: mysql:8.0.34
    environment:
      DATABASE_HOST: docker-mysql
      DATABASE_PORT: 3306
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: dockerdemodb
      MYSQL_USER: admin
      MYSQL_PASSWORD: root
