spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    initialization-mode: always
    url: jdbc:mysql://localhost:3306/dockerdemodb?autoReconnect=true&allowPublicKeyRetrieval=true&useSSL=false
    password: root
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
